project:
  type: website

website:
  title: "Heta Shah"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: "#summary"
        text: Summary
      - href: "#experience"
        text: Experience
      - href: "#projects"
        text: Projects
      - href: "#contact"
        text: Contact

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

editor: visual